baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'My New Hugo Site'

# Enable emoji in markdown
enableEmoji = true

# Pagination
paginate = 6
paginatePath = "page"

[params]
  description = "I turn coffee :coffee: into code, use tabs over spaces and never break production."
  favicon = "favicon.ico"
  images = ["me.jpg"]

[author]
  name = "Your Name"
  email = "your.email@example.com"

[taxonomies]
  tool = "tools"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/#experience"
    weight = 2
  [[menu.main]]
    name = "Skills"
    url = "/#skills"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 5


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
  tools = "/projects/tags/:slug/"


[outputs]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]


[params.social]
  [[params.social.links]]
    name = "GitHub"
    url = "https://www.github.com/samdc73"
    icon = "fa-brands fa-github"

  [[params.social.links]]
    name = "GitLab"
    url = "https://www.gitlab.com/samdc73"
    icon = "fa-brands fa-gitlab"

  [[params.social.links]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/samdc73"
    icon = "fa-brands fa-linkedin-in"

  [[params.social.links]]
    name = "Twitter"
    url = "https://twitter.com/samdc73"
    icon = "fab fa-twitter"

  [[params.social.links]]
    name = "Instagram"
    url = "https://www.instagram.com/samdc73"
    icon = "fab fa-instagram"

[params.experience]
  [[params.experience.items]]
    title = "Quality Analyst"
    company = "Natera"
    date = "2022 — current"
    description = "Main responsibilities and achievements:"
    bullets = [
      "Implemented automated testing procedures, reducing manual testing time by 40%",
      "Collaborated with cross-functional teams to improve product quality",
      "Developed and maintained comprehensive test plans and test cases"
    ]

  [[params.experience.items]]
    title = "IT Support"
    company = "Al-Aqeelah Takaful Insurance"
    date = "2014 — 2018"
    description = "Key contributions:"
    bullets = [
      "Provided technical support to over 100 employees, resolving hardware and software issues",
      "Implemented a new ticketing system, improving response time by 30%",
      "Conducted regular training sessions on IT security best practices"
    ]


[params.skills]
  [[params.skills.list]]
    name = "Python"
    image = "https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg" 

  [[params.skills.list]]
    name = "PyTorch"
    image = "https://raw.githubusercontent.com/devicons/devicon/master/icons/pytorch/pytorch-original.svg"

  [[params.skills.list]]
    name = "SQL"
    image = "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-plain.svg"

  [[params.skills.list]]
    name = "C++"
    image = "https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg"

    [[params.skills.list]]
    name = "HTML"
    image = "https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg"



[params.style]
  # Add any custom CSS classes here
  # customCSS = ["custom.css"]

[params.features]
  search = true
  portfolio = true
